Fix a potential bug when controller processes before AR connected
There is a chance that controller process invoke before AR establish a connection, this can cause `NoMethodError (undefined method `+' for nil:NilClass` while adding up 2 `nil` objects in `"SQL Queries: #{count + count_cache}"`.